service: xyz-form-cors-proxy

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  cors-proxy:
    handler: index.handler
    events:
      - http:
        method: post
        cors:
          origin: 'https://www.frequency.xyz'
          headers:
            - Content-Type
