<script>
  import MissionItem from '$components/Sections/Mission/MissionItem.svelte';
  import App from '$lib/assets/Mission/App.svg';
  import Box from '$lib/assets/Mission/Box.svg';
  import Fingerprint from '$lib/assets/Mission/Fingerprint.svg';
  import Network from '$lib/assets/Mission/Network.svg';
  import Universe from '$lib/assets/Mission/Universe.svg';
  import Users from '$lib/assets/Mission/Users.svg';

  const missionItems = [
    {
      iconAlt: 'Fingerprint',
      icon: Fingerprint,
      body: `A secure, self-sovereign <span class="font-bold text-primary">digital identity</span> solution that enables sign-in and seamless data sharing across applications.`,
    },
    {
      iconAlt: 'Users',
      icon: Users,
      body: `An open economy where users <span class="font-bold text-primary">share in the value</span> they create online.`,
    },
    {
      iconAlt: 'Network',
      icon: Network,
      body: `The option to leave applications and <span class="font-bold text-primary">take your data with you</span>.`,
    },
    {
      iconAlt: 'Box',
      icon: Box,
      body: `A <span class="font-bold text-primary">practical economic model</span> that enables scaled decentralization.`,
    },
    {
      iconAlt: 'Universe',
      icon: Universe,
      body: `Secure storage for personal data so it is not controlled by any application or company, and only accessible with <span class="font-bold text-primary">explicit permission</span>.`,
    },
    {
      iconAlt: 'App',
      icon: App,
      body: `An <span class="font-bold text-primary">interconnected, interoperable</span> environment for exchanging training data, including  metadata generated by user interactions, among open-source, <span class="font-bold text-primary">AI applications</span>.`,
    },
  ];
</script>

<div class="gap-f64 grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
  {#each missionItems as item (item.iconAlt)}
    <MissionItem>
      {#snippet icon()}
        <span><img src={item.icon} alt={item.iconAlt} /></span>
      {/snippet}
      {#snippet body()}
        <p>
          {@html item.body}
        </p>
      {/snippet}
    </MissionItem>
  {/each}
</div>
